config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'gists/index'
    delete 'gists/destroy'
  end

  get 'feedbacks/new'
  get 'feedbacks/create'

  root to: 'tests#index'


  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
              :controllers => { sessions: 'sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions,  only: :index do
      resources :answers,  only: :index
    end
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
   resources :gists, only: :index
   resources :badges
  end

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, alert: t('.success')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge), alert: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, alert: t('.success')
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :image, :rule, :parametr)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class='align-middle'><%= badge.title %></td>
  <td class='align-middle'><%= badge.image %></td>
  <td class='align-middle'><%= link_to t('common.button.open'), admin_badge_path(badge) %></td>
  <td class='align-middle'><%= link_to t('common.button.update'), edit_admin_badge_path(badge) %></td>
  <td class='align-middle'><%= link_to t('common.button.delete'), admin_badge_path(badge),
                                             method: :delete,
                                             data: { confirm: t('common.pop_up.delete') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :image %><br>
    <%= form.text_field :image %>
  </p>

  <p>
    <%= form.label :rule %><br>
    <%= form.select :rule, options_for_select([
      ['category_complete'],
      ['first_try'],
      ['level_complete'],
      ]) %>
  </p>

  <p>
    <%= form.label :parametr %><br>
    <%= form.text_field :parametr %>
  </p>

  <p><%= form.submit %></p>
<% end %>
<%= link_to 'Back',  admin_badges_path %>

app/views/admin/badges/edit.html.erb
<%= render 'form' %>

app/views/admin/badges/index.html.erb
<%= link_to t('.badges'), new_admin_badge_path %>
<table class="table">
  <%= render @badges %>
</table>

app/views/admin/badges/new.html.erb
<%= render 'form' %>

app/views/admin/badges/show.html.erb
<%= render 'form' %>