config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'gists/index'
    delete 'gists/destroy'
  end

  get 'feedbacks/new'
  get 'feedbacks/create'

  root to: 'tests#index'


  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
              :controllers => { sessions: 'sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions,  only: :index do
      resources :answers,  only: :index
    end
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
   resources :gists, only: :index
   resources :badges
  end

end

app/models/admin.rb
class Admin < User

  validates :first_name, :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_count_answer, on: :create

  private
  def validate_count_answer
    errors.add(:restriction, 'Максимум 4 ответа') if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(created_at: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists

  validates :body, presence: true

end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :author, class_name: "User", foreign_key: :author_id
  has_many :questions, dependent: :destroy

  has_many :test_passages
  has_many :users, through: :test_passages

  scope :by_category, ->(title) { joins(:category)
                                  .where(categories: { title: title })
                                  .order(title: :desc)
                                }
  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  validates :title, presence: true
  validates :level, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  #validate :one_title_one_level
  validates :title, uniqueness: { scope: :level}

  def self.with_category(title)
    by_category(title).pluck(:title)
  end

  # def one_title_one_level
  #   errors.add(:title)if self.class.where("level = ? AND title = ?", level, title).count > 1
  # end
  # def timer_exists? rails сгенерировал функцию timer?
  #   timer && timer > 0
  # end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.current_question = next_question
    save!
  end

  def result
    (100 * self.correct_questions / test.questions.count.to_f).round(1)
  end

  def passed?
    result >= 85 ? self.update(success: true) : false
  end

  def total_questions_count
    test.questions.count
  end

  def number_current_question
    test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def successfully?
    completed? && passed?
  end

  def finish!
    self.current_question = nil
  end

  def successfully?
    completed? && passed?
  end

  def time_left
    (expires_at - Time.current).to_i
  end

  def time_over?
    expires_at < Time.now
  end

  # def finish!
  #   self.current_question = nil
  # end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    remaining_questions.first
  end

  def remaining_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def expires_at
    created_at + test.timer.minutes
  end

end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/traveled_test.rb
class TraveledTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
#require 'digest/sha1'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable
  #include Auth
  #has_secure_password
  #has_many :own_tests, class_name: "Test", dependent: :nullify
  has_many :feedbacks
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :authored_tests, class_name: 'Test', foreign_key: :author_id
  has_many :gists
  has_many :user_badges
  has_many :badges, through: :user_badges

  def tests_by_level(level)
    tests.where(level: level)
  end

  def admin?
    self.is_a?(Admin)
  end

  def full_name
    "#{last_name} #{first_name}"
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def username
    if full_name.blank?
      self.email.split('@')[0]
    else
      self.full_name
    end
  end

end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  def hash_gists(gist)
    gist.url.split('/').last
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(resource)
    if resource.new_record?
      "Create New #{@test.title} Question"
    else
      "Edit #{resource.test.title} Question"
    end
#    debugger
  end
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
=begin    if test.level > 10
      'hard'
    elsif test.level > 0
      'midlle'
    else
      'elementary'
    end
=end
  end
end

app/views/admin/_nav.html.erb
<div class="navbar bg-light" >
  <%= link_to "TestGuru", root_path, class: "navbar-brand text-secondary" %>
  <div class="nav">
    <b><%=current_user.email %> </b> &nbsp;|&nbsp;
    <b><%= link_to 'Admin Panel', admin_tests_path, class: 'text-dark' %></b> &nbsp;|&nbsp;
    <b><%= link_to 'Gists', admin_gists_index_path, class: 'text-dark' %></b> &nbsp;|&nbsp;
    <b><%= link_to 'Badges', admin_badges_path, class: 'text-dark' %>
    </b> &nbsp;|&nbsp;
    <b><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'text-dark' %></b>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>

  <%= content_tag :div, class: 'resource-errors', data: {resource_id: resource.id } do %>
      <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li > <%= message %></li>
      <% end %>
      </ul>

  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message, class: "alert alert-#{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<hr>
  <div class="col-center text-center text-muted">
    <h6>Current year - <%= current_year %> </h6>
    <h6>Author: Kveladze_Yevgeniy </h6>
    <%=link_to 'Форма обратной связи', feedbacks_new_path %>
    <%= link_to  'GitHub', github_url("Zheka1988", "TestGuru") %>
    <p>Учебный проект в онлайн-школе <a href='http://thinknetica.com' target='_blank'>Thinknetika</a></p>
  </div>

app/views/shared/_header.html.erb
<table width="100%">
  <tr>
    <td > <h1 class = "logo" > TESTGURU </h1> </td>
      <td align = "right" class = "user panel" with = "15%"> <%= link_to 'Login', sessions_new_path %> |
        <%= link_to 'Signup', users_new_path %> |
        <%= link_to 'Exit', exit_path %>
      </td>
  </tr>

</table>

app/views/shared/_header_in.html.erb
<table width="100%">
  <tr>
    <td > <h1 class = "logo" > TESTGURU </h1> </td>
      <td align = "right" class = "user panel" with = "15%">
        <%= link_to 'Exit', exit_path %>
      </td>
  </tr>

</table>

app/views/shared/_header_out.html.erb
<table width="100%">
  <tr>
    <td > <h1 class = "logo" > TESTGURU </h1> </td>
      <td align = "right" class = "user panel" with = "15%"> <%= link_to 'Login', login_path %> |
        <%= link_to 'Signup', signup_path %>
      </td>
  </tr>

</table>

app/views/shared/_nav.html.erb
<div class="navbar navbar-light bg-light">
  <%= link_to "TestGuru", root_path, class: "navbar-brand" %>

  <span class="navbar-text bg-light">
    <% if user_signed_in? %>
      <b><%=current_user.email %></b> &nbsp;|&nbsp;
      <% if current_user.admin? %>
        <%= link_to 'Admin Panel', admin_tests_path %> &nbsp;|&nbsp;
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Badges', badges_path %> &nbsp;|&nbsp;
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% end %>
    <% else %>
      <%= link_to "Log in", new_session_path(resource_name) %> &nbsp;|&nbsp;
      <%= link_to "Sign up", new_registration_path(resource_name) %>
    <% end %>
  </span>
</div>

app/views/shared/_question.html.erb
  <tr>
    <td><%=  question.body %></td>
    <td><%= link_to 'Show', admin_question_path(question) %></td>
    <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>
    <td><%= link_to 'Delete',
                  admin_question_path(question),
                  method: :delete,
                  data: { confirm: 'Are you sure?' }%></td>
  </tr>

app/views/shared/_render_tests.html.erb
<% resource.each do |test| %>
  <tr>
    <td> <%= test.title %> </td>
      <td> <%= test.level %> </td>
      <td> <%= User.find(test.author_id).name %> </td>
      <td> <%= test.questions.count %></td>
      <td> <%=link_to "Edit",  edit_test_path(test) %></td>
      <td> <%= link_to "Show", test_path(test) %></td>
      <td> <%= link_to "Delete",
                    test_path(test),
                    method: :delete,
                    data: { confirm: 'Areyou sure?' } %></td>
  </tr>
<% end %>