config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'gists/index'
    delete 'gists/destroy'
  end

  get 'feedbacks/new'
  get 'feedbacks/create'

  root to: 'tests#index'


  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
              :controllers => { sessions: 'sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions,  only: :index do
      resources :answers,  only: :index
    end
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
   resources :gists, only: :index
   resources :badges
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists

  validates :body, presence: true

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.current_question = next_question
    save!
  end

  def result
    (100 * self.correct_questions / test.questions.count.to_f).round(1)
  end

  def passed?
    result >= 85 ? self.update(success: true) : false
  end

  def total_questions_count
    test.questions.count
  end

  def number_current_question
    test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def successfully?
    completed? && passed?
  end

  def finish!
    self.current_question = nil
  end

  def successfully?
    completed? && passed?
  end

  def time_left
    (expires_at - Time.current).to_i
  end

  def time_over?
    expires_at < Time.now
  end

  # def finish!
  #   self.current_question = nil
  # end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    remaining_questions.first
  end

  def remaining_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def expires_at
    created_at + test.timer.minutes
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!

  before_action  :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.html_url.present?
      current_user.gists.create(question: @test_passage.current_question, url: result.html_url)
       flash.notice = t('.success', url: result.html_url)
    else
       flash.alert = t('.failure')
    end

    redirect_to @test_passage
  end

  def update
    if @test_passage.time_over?
      @test_passage.current_question = nil
      next_action
    else
      @test_passage.accept!(params[:answer_ids])
      next_action
    end
  end

  private

  # def complete_test
  #   @test_passage.current_question = nil
  #   send_mail
  #   redirect_to result_test_passage_path(@test_passage)
  # end

  def next_action
    if @test_passage.completed?
      send_mail
      @test_passage.user.badges << BadgeService.new(@test_passage).call
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def send_mail
    TestsMailer.completed_test(@test_passage).deliver_now
  end

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.result_title', title: @test_passage.test.title) %></h1>

<% if @test_passage.passed? %>
  <h2 class='text-success'> Тест успешно пройден! <br>
    Вы выполнили: <%= @test_passage.result %> %
  </h2>
<% else %>
  <h2 class='text-danger'> Тест не пройден, попробуйте еще раз! <br>
    Вы выполнили: <%= @test_passage.result %> %
  </h2>
<% end %>



<%= link_to 'Main', tests_path %>

app/views/test_passages/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-auto">
    <h3 class="text-center text-muted text-sm"><%= t('.header', title: @test_passage.test.title) %></h3>
    <p>
      <% if @test_passage.test.timer? %>
        Time left: <%= content_tag :span, '', class: 'timer', data: { timer:  @test_passage.time_left } %>
      <% end %>
    </p>
    <div class = "text-sm-left text-info">
      <%= t('.number_q')%> <%= @test_passage.total_questions_count %> <br>
      <%= t('.count_q')%><%= @test_passage.number_current_question %>
    </div>
    <b class="text-dark">
      <%= @test_passage.current_question.body %>
    </b>
    <div class="form-check">
        <%= form_with url: test_passage_path(@test_passage), local: true, id: :check, method: :put do |form| %>
          <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
              <div class="col">
                <%= b.check_box id: "answer_ids_#{b.object.id}", class: 'form-check-input' %>
                <%= b.label %>
              </div>
          <% end %>
          <p><%= link_to t('.gist'), gist_test_passage_path(@test_passage), method: :post %></p>
          <p><%= form.submit 'Next', class: 'btn btn-outline-primary btn-sm next' %></p>
        <% end %>
    <%= content_tag :div, class: 'myProgress' do %>
        <%= content_tag :div,
                class: ['progress-bar', 'bg-danger'],
                value: @test_passage.number_current_question,
                max: @test_passage.total_questions_count do %>
        <% end %>
    <% end %>


    </div>
  </div>
</div>