config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'gists/index'
    delete 'gists/destroy'
  end

  get 'feedbacks/new'
  get 'feedbacks/create'

  root to: 'tests#index'


  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
              :controllers => { sessions: 'sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions,  only: :index do
      resources :answers,  only: :index
    end
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
   resources :gists, only: :index
   resources :badges
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_count_answer, on: :create

  private
  def validate_count_answer
    errors.add(:restriction, 'Максимум 4 ответа') if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :set_question, only: [:new, :create]
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def new
    @answer = @question.answers.new
  end

  def show; end

  def edit; end

  def create
    @answer = @question.answers.build(answer_params)
    if @answer.save
      redirect_to admin_answer_path(@answer)
    else
      # render plain: "#{@answer.errors.full_messages}"
      #redirect_to admin_question_path(@question)
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private
  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to 'Show', answer_path(answer) %> |
  <%= link_to 'Edit', edit_answer_path(answer) %> |
  <%= link_to 'Delete', answer_path(answer),
               method: :delete,
               data: { confirm: 'Are you sure?' }%>

</li>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer], local: true do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>
  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct%>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit Answer</h1>
<p>
  <%= @answer.body %>
</p>

<%= render 'form' %>
<%= link_to 'Back', answer_path(@answer) %>

app/views/answers/new.html.erb
<h1>Create new answer</h1>
<p>
  <%= @question.body %>
</p>
<%= render 'form' %>
<%= link_to 'Back', question_path(@question) %>

app/views/answers/show.html.erb
<h1>Question</h1>
<p>
  <%= @answer.question.body %>
</p>

  <h2>Body: </h2>
<p>
  <%= @answer.body %>
</p>
<h2>Correct: </h2>
<p>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', question_path(@answer.question) %>